/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.jacky;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_help=0x7f020000;
        public static final int ic_new_game=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int speaker32=0x7f020003;
    }
    public static final class id {
        public static final int bt_false=0x7f070012;
        public static final int bt_true=0x7f070011;
        public static final int btnClear=0x7f07001e;
        public static final int btnGenerate=0x7f07001d;
        public static final int btnNewWrod=0x7f070018;
        public static final int btnOKDialog=0x7f070003;
        public static final int btnPlan=0x7f070017;
        public static final int btnStudy=0x7f070015;
        public static final int btnVoidStudy=0x7f070016;
        public static final int btnWordList=0x7f070014;
        public static final int button_bar=0x7f070010;
        public static final int dpStartDate=0x7f07001c;
        public static final int help=0x7f070022;
        public static final int imgLine1=0x7f070006;
        public static final int imgLine2=0x7f070009;
        public static final int img_speak=0x7f070008;
        public static final int layout_root=0x7f070000;
        public static final int lbl_example=0x7f07000e;
        public static final int linearLayout=0x7f07001f;
        public static final int linearLayout1=0x7f070013;
        public static final int listView=0x7f070020;
        public static final int new_game=0x7f070021;
        public static final int relativeLayout1=0x7f070004;
        public static final int scrollPart=0x7f07000b;
        public static final int scrollView1=0x7f07000a;
        public static final int textDialog=0x7f070001;
        public static final int textView1=0x7f070019;
        public static final int textView2=0x7f07001b;
        public static final int timePickerDialog=0x7f070002;
        public static final int txtWordPerDay=0x7f07001a;
        public static final int txt_description=0x7f07000d;
        public static final int txt_example=0x7f07000f;
        public static final int txt_pron=0x7f070007;
        public static final int txt_shiyi=0x7f07000c;
        public static final int txt_word=0x7f070005;
    }
    public static final class layout {
        public static final int customdialog=0x7f030000;
        public static final int dic=0x7f030001;
        public static final int main=0x7f030002;
        public static final int plan=0x7f030003;
        public static final int wordlist=0x7f030004;
    }
    public static final class menu {
        public static final int hello_menu=0x7f060000;
    }
    public static final class raw {
        public static final int ites=0x7f040000;
    }
    public static final class string {
        public static final int app_name=0x7f050001;
        public static final int hello=0x7f050000;
        public static final int help=0x7f050003;
        public static final int level=0x7f050005;
        public static final int new_game=0x7f050002;
        public static final int plan=0x7f050004;
        public static final int start=0x7f050006;
    }
}
